baseURL: "https://lzprezip.netlify.app/"
languageCode: "en-us"
title: "Li Zhipeng's Portfolio | UX designer"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
